// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 11.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace FDACodedUITests_Framework.UIMaps.AllSiteContentPageUIMapClasses
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public partial class AllSiteContentPageUIMap
    {
        
        /// <summary>
        /// Navigate to the "Shared Documents" library
        /// </summary>
        public void OpenSharedDocumentsLibrary()
        {
            #region Variable Declarations
            HtmlHyperlink sharedDocumentsHyperlink = this.AllSiteContentBrowser.AllSiteContentPage.SharedDocumentsHyperlink;
            #endregion

            // Click 'Shared Documents' link
            Mouse.Click(sharedDocumentsHyperlink, new Point(69, 10));
        }
        
        #region Properties
        public AllSiteContentBrowser AllSiteContentBrowser
        {
            get
            {
                if ((this.mAllSiteContentBrowser == null))
                {
                    this.mAllSiteContentBrowser = new AllSiteContentBrowser();
                }
                return this.mAllSiteContentBrowser;
            }
        }
        #endregion
        
        #region Fields
        private AllSiteContentBrowser mAllSiteContentBrowser;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class AllSiteContentBrowser : BrowserWindow
    {
        
        public AllSiteContentBrowser()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("All Site Content");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public AllSiteContentPage AllSiteContentPage
        {
            get
            {
                if ((this.mAllSiteContentPage == null))
                {
                    this.mAllSiteContentPage = new AllSiteContentPage(this);
                }
                return this.mAllSiteContentPage;
            }
        }
        #endregion
        
        #region Fields
        private AllSiteContentPage mAllSiteContentPage;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class AllSiteContentPage : HtmlDocument
    {
        
        public AllSiteContentPage(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "All Site Content";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/_layouts/viewlsts.aspx";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://sharepoint.preprod.fda.gov/_layouts/viewlsts.aspx";
            this.WindowTitles.Add("All Site Content");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink SharedDocumentsHyperlink
        {
            get
            {
                if ((this.mSharedDocumentsHyperlink == null))
                {
                    this.mSharedDocumentsHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mSharedDocumentsHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = "viewlistDocumentLibrary";
                    this.mSharedDocumentsHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mSharedDocumentsHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mSharedDocumentsHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Shared Documents";
                    this.mSharedDocumentsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/Shared%20Documents/Forms/AllItems.aspx";
                    this.mSharedDocumentsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mSharedDocumentsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://sharepoint.preprod.fda.gov/Shared%20Documents/Forms/AllItems.aspx";
                    this.mSharedDocumentsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mSharedDocumentsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "id=viewlistDocumentLibrary href=\"/Shared";
                    this.mSharedDocumentsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "84";
                    this.mSharedDocumentsHyperlink.WindowTitles.Add("All Site Content");
                    #endregion
                }
                return this.mSharedDocumentsHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mSharedDocumentsHyperlink;
        #endregion
    }
}
